import Head from "next/head";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import Link from "next/dist/client/link";

export default function Home({ movies }) {
  return (
    <div>
      <Head>
        <title>The Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <div className="w-full sm:w-9/12 container mx-auto">
        <h3 className="text-center text-3xl p-12 text-white font-semibold">
          Popüler Filmler
        </h3>

        <div className="grid grid-cols-1  sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-5  gap-x-8 gap-y-8 ">
          {movies.results.map((movie, index) => (
            <div
              key={index}
              className="flex items-stretch justify-center lg:justify-start overflow-hidden relative rounded-xl"
            >
              {" "}
              <Link href={`/movie/${movie.id}`}>
                <span className="relative group block flex-shrink-0">
                  <div className="absolute inset-0 bg-black bg-opacity-70 hidden group-hover:flex flex-col justify-end text-white px-4 py-4 cursor-pointer">
                    <div>
                      <h4>{movie.release_date}</h4>
                      <h3 className="text-lg mb-2">{movie.title}</h3>
                      <p className="leading-normal truncate">
                        {movie.overview}
                      </p>
                    </div>
                  </div>

                  <img
                    src={`https://www.themoviedb.org/t/p/w220_and_h330_face${movie.poster_path}`}
                    alt="#"
                    className="w-full object-cover object-top"
                  />
                </span>
              </Link>
            </div>
          ))}
        </div>
      </div>
      <Footer />
    </div>
  );
}

export async function getServerSideProps() {
  const request = await fetch(
    `https://api.themoviedb.org/3/movie/popular?api_key=06d452763ff3255d50542e9e95b2634b&language=tr-TR&page=1`
  );
  const movies = await request.json();
  return {
    props: {
      movies,
    },
  };
}
