import Head from "next/head";
import Navbar from "../components/Navbar";

export default function Home({ movies }) {
  console.log(movies.results);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <div className="w-full sm:w-9/12 container mx-auto mt-8">
        <h3>Popüler Filmler</h3>

        <div className="grid grid-cols-1  sm:grid-cols-2 lg:grid-cols-5  gap-x-8 gap-y-8 ">
          {movies.results.map((movie, index) => (
            <div
              key={index}
              className="flex items-stretch justify-center lg:justify-start overflow-hidden relative"
            >
              <a href="#" className="relative group block flex-shrink-0">
                <div className="absolute inset-0 bg-black opacity-75 hidden group-hover:flex flex-col justify-end text-white px-4 py-4 cursor-pointer">
                  <div>
                    <h3 className="text-lg mb-2">{movie.original_title}</h3>
                    <p className="leading-normal truncate">{movie.overview}</p>
                  </div>
                </div>

                <img
                  src={`https://www.themoviedb.org/t/p/w220_and_h330_face${movie.poster_path}`}
                  alt="#"
                  className="w-full object-cover object-top"
                />
              </a>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const request = await fetch(
    `https://api.themoviedb.org/3/movie/popular?api_key=06d452763ff3255d50542e9e95b2634b&language=en-US&page=1`
  );
  const movies = await request.json();
  return {
    props: {
      movies,
    },
  };
}
